include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener"
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: settings_reset
